stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: samilee.me
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./k8s/deployment.yaml
timeout: 60
notification: {}
